# Generated by Django 4.2 on 2025-02-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='comision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
