# Generated by Django 4.2 on 2025-02-17 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cursos_comision_alter_cursos_nombre'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='telefono',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='cursos.cursos'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Inscripciones',
        ),
    ]
